version: "3.8"


services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_SOURCE=${DB_SOURCE}
    depends_on:
      - postgres
    restart: always
    command: [ "/app/main" ]

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports: 
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}



